name = "sanrize-shop-fe" # Replace with your Cloudflare Pages project name if different
compatibility_date = "2024-05-15" # Specifies the compatibility date for Workers APIs
compatibility_flags = ["nodejs_compat"] # Enable Node.js compatibility

# Environment variables for the production environment
# These can also be set in the Cloudflare Pages dashboard.
# IMPORTANT: Replace YOUR_PRODUCTION_BASE_API_URL_HERE with your actual API URL.
[env.production.vars]
BASE_API_URL = "YOUR_PRODUCTION_BASE_API_URL_HERE"
# NODE_VERSION = "18" # If you need to specify a Node.js version for Cloudflare Pages build

# For local development using `wrangler pages dev`:
# The build command from package.json ("npx @cloudflare/next-on-pages") will be used.
# Output will typically be in .vercel/output/static.
# `wrangler pages dev .vercel/output/static` can be used to serve the built output.
#
# If you want to define local-only environment variables for `wrangler pages dev`,
# you can use a .dev.vars file (make sure to .gitignore it) or uncomment and use [vars] below.
# [vars]
# BASE_API_URL = "http://localhost:your_local_api_port" # Example for local dev

# Note: When deploying with `wrangler pages deploy`, after running `npm run build` (which executes `npx @cloudflare/next-on-pages`),
# you should deploy the output directory generated by `next-on-pages`.
# This is typically `.vercel/output/static`.
# So the command would be: `npm run build && wrangler pages deploy .vercel/output/static`
